-- Uruchom w Supabase: SQL Editor → New query.
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 50),
  email text not null check (char_length(email) between 5 and 200),
  rating smallint not null check (rating between 1 and 5),
  content text not null check (char_length(content) between 5 and 700),
  images text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.reviews add column if not exists images text[] not null default '{}';

alter table public.reviews enable row level security;

drop policy if exists "Public can submit reviews" on public.reviews;
create policy "Public can submit reviews"
on public.reviews for insert to anon
with check (status = 'pending');

drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can read approved reviews"
on public.reviews for select to anon
using (status = 'approved');

-- Zamówienia przechowuje wyłącznie funkcja serwerowa używająca service role.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  stripe_session_id text unique,
  customer jsonb not null,
  items jsonb not null,
  total integer not null,
  currency text not null default 'pln',
  status text not null default 'created',
  cancelled_at timestamptz,
  cancellation_reason text,
  cancellation_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.orders enable row level security;

-- Prywatna lista administratorów. Użytkownika tworzy się w Authentication,
-- a następnie dodaje jego UUID do tej tabeli.
create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select exists(select 1 from public.admin_users where id = auth.uid()) $$;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Admins can manage reviews" on public.reviews;
create policy "Admins can manage reviews" on public.reviews
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admin can see own role" on public.admin_users;
create policy "Admin can see own role" on public.admin_users
for select to authenticated using (id = auth.uid());

create table if not exists public.products (
  id text primary key,
  name_pl text not null,
  name_en text,
  description_pl text not null default '',
  description_en text not null default '',
  availability_pl text not null default 'Dostępny',
  availability_en text not null default 'Available',
  shipping_time_pl text not null default 'Wysyłka w 1–3 dni robocze',
  shipping_time_en text not null default 'Ships within 1–3 business days',
  price integer not null check (price >= 0),
  category text not null default 'classic' check (category in ('small','classic','large')),
  height text,
  width text,
  pieces text,
  badge_pl text,
  badge_en text,
  main_image text,
  gallery text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.products add column if not exists availability_pl text not null default 'Dostępny';
alter table public.products add column if not exists availability_en text not null default 'Available';
alter table public.products add column if not exists shipping_time_pl text not null default 'Wysyłka w 1–3 dni robocze';
alter table public.products add column if not exists shipping_time_en text not null default 'Ships within 1–3 business days';
alter table public.products enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products
for select to anon, authenticated using (active = true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products" on public.products
for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('product-images','product-images',true)
on conflict (id) do update set public = true;

drop policy if exists "Public product images" on storage.objects;
create policy "Public product images" on storage.objects
for select to public using (bucket_id = 'product-images');

drop policy if exists "Admins upload product images" on storage.objects;
create policy "Admins upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins update product images" on storage.objects;
create policy "Admins update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_admin()) with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins delete product images" on storage.objects;
create policy "Admins delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

insert into storage.buckets (id, name, public)
values ('review-images','review-images',true)
on conflict (id) do update set public = true;

drop policy if exists "Public review images" on storage.objects;
create policy "Public review images" on storage.objects
for select to public using (bucket_id = 'review-images');

drop policy if exists "Public upload review images" on storage.objects;
create policy "Public upload review images" on storage.objects
for insert to anon with check (bucket_id = 'review-images');

drop policy if exists "Admins delete review images" on storage.objects;
create policy "Admins delete review images" on storage.objects
for delete to authenticated using (bucket_id = 'review-images' and public.is_admin());

insert into public.products (id,name_pl,name_en,description_pl,description_en,price,category,height,width,pieces,badge_pl,badge_en,main_image,gallery,active,sort_order) values
('szyszka-12','Bursztynowa szyszka','Amber pinecone','Mała forma, wielki blask. Stabilna drewniana podstawa.','A small form with a beautiful glow on a stable wooden base.',58,'small','11–12 cm','7–8 cm','50–60','Na dobry początek','A perfect start','647ee3324afdb8d8820013c96e59.webp',array['647ee3324afdb8d8820013c96e59.webp','ba20276641c2b6a262ec2b774fff.webp'],true,10),
('drzewko-216','Drzewko 216 kamieni','216-stone tree','Subtelne drzewko na naturalnym korzeniu dębu lub mopani.','A delicate tree set on natural oak or mopani root.',218,'small','17 cm','—','216','Bestseller','Bestseller','assets/drzewko-216-glowne.webp',array['assets/drzewko-216-glowne.webp','assets/drzewko-216-skala.webp','assets/drzewko-216-detal.webp','assets/drzewko-216-wariant.webp'],true,20),
('szyszka-zlota-20','Szyszka złota','Golden pinecone','Złota szyszka pokryta bursztynem w odcieniu koniakowym.','A golden pinecone covered with cognac-toned Baltic amber.',260,'classic','20 cm','16–17 cm','350–400','Klasyk','Classic','assets/szyszka-zlota-20.webp',array['assets/szyszka-zlota-20.webp','ba20276641c2b6a262ec2b774fff.webp','647ee3324afdb8d8820013c96e59.webp'],true,30),
('drzewko-klasyczne-20','Drzewko klasyczne','Classic amber tree','432 bryłki bursztynu na ręcznie modelowanych gałązkach.','432 amber stones set on individually shaped branches.',378,'classic','20 cm','—','432','Najczęściej wybierane','Most popular','Drzewko-szczescia-BURSZTYN_prezent.webp',array['Drzewko-szczescia-BURSZTYN_prezent.webp','Drzewko-szczescia-BURSZTYN_prezent-Wysokosc-maksymalna-20-cm.webp','Drzewko-szczescia-BURSZTYN_prezent-Marka-bez-marki.webp','Drzewko-szczescia-BURSZTYN_prezent-Kod-producenta-bizuteria-prezent-bursztyn-dom-dekoracja.webp'],true,40),
('drzewko-premium-20','Drzewko Premium','Premium amber tree','Pełna korona z bursztynu i starannie wybrana podstawa.','A full amber crown paired with a carefully selected base.',398,'classic','20 cm','—','432','Unikatowa podstawa','Unique base','e019315a413d9b4eaec70e40b0ca.webp',array['e019315a413d9b4eaec70e40b0ca.webp','c32eb4ae42e7a621643233cc3711.webp','Drzewko-szczescia-BURSZTYN_prezent-Marka-bez-marki.webp'],true,50),
('drzewko-duze-25','Drzewko 648 kamieni','648-stone tree','Okazała kompozycja do wnętrza lub na wyjątkowy prezent.','A statement composition for an interior or exceptional gift.',598,'large','25 cm','—','648','Okazałe','Statement piece','c32eb4ae42e7a621643233cc3711.webp',array['c32eb4ae42e7a621643233cc3711.webp','e019315a413d9b4eaec70e40b0ca.webp','assets/drzewko-216-glowne.webp'],true,60)
on conflict (id) do nothing;
