// Uzupełnij po utworzeniu projektu Supabase. Klucz anon jest przeznaczony do użycia w przeglądarce.
window.AMBERFLO_CONFIG = {
  supabaseUrl: "https://mptzogdtgwymlmuqmtmo.supabase.co",
  supabaseAnonKey: "sb_publishable_2Y08OvWajFFqEnLKY2K26A_fBU9hEUp",
  adminEmail: "biuroamberflo@gmail.com",
  // Publiczny token Geowidget z manager.paczkomaty.pl (API -> Geowidget).
  inpostGeowidgetToken: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzQlpXVzFNZzVlQnpDYU1XU3JvTlBjRWFveFpXcW9Ua2FuZVB3X291LWxvIn0.eyJleHAiOjIwOTkyNTQxODIsImlhdCI6MTc4Mzg5NDE4MiwianRpIjoiZjMwMGQwYjgtYTY3NC00NzQ0LTgzZjMtNzA1ZjM0NTEyOTlmIiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5pbnBvc3QucGwvYXV0aC9yZWFsbXMvZXh0ZXJuYWwiLCJzdWIiOiJmOjEyNDc1MDUxLTFjMDMtNGU1OS1iYTBjLTJiNDU2OTVlZjUzNTo0YVpjaWJpVzBxVDl3Z2E0VWM2WlVndlkyc0t0QU9Yb0l3em1GTlItZDFnIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2hpcHgiLCJzZXNzaW9uX3N0YXRlIjoiNjJhZDgyZGUtYTJiZS00MDE3LWFhZGYtOTBmMjc2OTA1YjgwIiwic2NvcGUiOiJvcGVuaWQgYXBpOmFwaXBvaW50cyIsInNpZCI6IjYyYWQ4MmRlLWEyYmUtNDAxNy1hYWRmLTkwZjI3NjkwNWI4MCIsImFsbG93ZWRfcmVmZXJyZXJzIjoiYW1iZXJmbG8ucGwiLCJ1dWlkIjoiOTA4NDAxM2MtYmNkNC00ZTdkLWI1MzEtNWZlY2MwZGRkYzExIn0.hl6a8IjVuT83VoG5gGCohKvblo-9kf5jJUr4bbys63WRkd1DKfzKTF62EC2E60dIWaAulQyW_mgmLvvZYHdQpGVSXDJhEayQe21430FAMMyDLWl75Kw3IXhutgUQYt-yZ0ovlfpWdq4gYnpU0YEgIYuhTSSB3UBFrs5w84MOFbLFJCIrMMMSXi_i3uMnKjkkxolYLb5uN5hbOar3q7_cfLO2yI-JpNqDB2nT1O2bhb3K0aJnmdDclWg5JC5t1V3B9xRim_suhr9wzoTB1y4tCeAhiWD8_FF1xSVem2sOEPzNg9lAZ1pXTKGYPotIZOXNPZHCUFVs_FImQZN2_25XmQ"
};
