// Uzupełnij po utworzeniu projektu Supabase. Klucz anon jest przeznaczony do użycia w przeglądarce.
window.AMBERFLO_CONFIG = {
  supabaseUrl: "https://mptzogdtgwymlmuqmtmo.supabase.co",
  supabaseAnonKey: "sb_publishable_2Y08OvWajFFqEnLKY2K26A_fBU9hEUp",
  adminEmail: "biuroamberflo@gmail.com",
  // Publiczny token Geowidget z manager.paczkomaty.pl (API -> Geowidget).
  inpostGeowidgetToken: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzQlpXVzFNZzVlQnpDYU1XU3JvTlBjRWFveFpXcW9Ua2FuZVB3X291LWxvIn0.eyJleHAiOjIwOTg2MTYzOTUsImlhdCI6MTc4MzI1NjM5NSwianRpIjoiZGZjZDhhNDYtZjBiYS00ZDRmLWFkNGYtMTlhZDdiZWY4OTVhIiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5pbnBvc3QucGwvYXV0aC9yZWFsbXMvZXh0ZXJuYWwiLCJzdWIiOiJmOjEyNDc1MDUxLTFjMDMtNGU1OS1iYTBjLTJiNDU2OTVlZjUzNTo0YVpjaWJpVzBxVDl3Z2E0VWM2WlVndlkyc0t0QU9Yb0l3em1GTlItZDFnIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2hpcHgiLCJzZXNzaW9uX3N0YXRlIjoiNGJlOTJhNmUtZDg4Ni00ZTk3LTgwYWYtMDU1NmI2MDNhMjczIiwic2NvcGUiOiJvcGVuaWQgYXBpOmFwaXBvaW50cyIsInNpZCI6IjRiZTkyYTZlLWQ4ODYtNGU5Ny04MGFmLTA1NTZiNjAzYTI3MyIsImFsbG93ZWRfcmVmZXJyZXJzIjoibWFyZmxvcmN6YWsuZ2l0aHViLmlvIiwidXVpZCI6IjkwODQwMTNjLWJjZDQtNGU3ZC1iNTMxLTVmZWNjMGRkZGMxMSJ9.QFKkN5D95GJ8qVysCM-I03PKi2AADJlOadh8ZlfB9qv2C1IZQayCF9misA1699xXKgf6ApCpZqkonWMSf2z05lCsc1TWEGdVf0jyCJ0-VFRUmgyAKkeoR2dlJMxi-IVA09ewx09QPhQwSf_SZ5Bp9LvfIrNcMHYVXm_ZCbpzNnSSpsR-a84FTy3fZ5h5HbJJRlnhF-SiLHgAVmTJ3qMlKp_HvmpRm01UUBrrZ0seX_jLhiVv0qBlRrjweOkNBzr7Tc0blJ_lc9RJAc0TdbgOv6oBzS5-uptnXgk9ZEvwPFWuGpvlPmPQPWYmubH_U8-UKQ8oBvuyJGbeipZkfbJpmA"
};
